version: "3.3"
services:
  web:
    build: .
    ports:
      - "443:8000"
    volumes:
      - .:/code
    command: sh -c "pip install -r requirements.txt && gunicorn --certfile=theturinggames.crt --keyfile=theturinggames.key -b 0.0.0.0:8000 -w 4 app.wsgi:app"